ALTER TABLE EMP_INFO
  DROP
    CONSTRAINT FK_BRANCH_TO_EMP_INFO
    CASCADE;

ALTER TABLE TICKET_PAY
  DROP
    CONSTRAINT FK_USER_INFO_TO_TICKET_PAY
    CASCADE;

ALTER TABLE TICKET_PAY
  DROP
    CONSTRAINT FK_MOVIE_INFO_TO_TICKET_PAY
    CASCADE;

ALTER TABLE TICKET_PAY
  DROP
    CONSTRAINT FK_BRANCH_TO_TICKET_PAY
    CASCADE;

ALTER TABLE EMP_TIMEMANAGE
  DROP
    CONSTRAINT FK_EMP_INFO_TO_EMP_TIMEMANAGE
    CASCADE;

ALTER TABLE USER_MILEAGE
  DROP
    CONSTRAINT FK_USER_INFO_TO_USER_MILEAGE
    CASCADE;

ALTER TABLE BRANCH_MOVIE
  DROP
    CONSTRAINT FK_MOVIE_INFO_TO_BRANCH_MOVIE
    CASCADE;

ALTER TABLE USER_INFO
  DROP
    PRIMARY KEY
    CASCADE
    KEEP INDEX;

ALTER TABLE EMP_INFO
  DROP
    PRIMARY KEY
    CASCADE
    KEEP INDEX;

ALTER TABLE TICKET_PAY
  DROP
    PRIMARY KEY
    CASCADE
    KEEP INDEX;

ALTER TABLE CAR_MANAGE
  DROP
    PRIMARY KEY
    CASCADE
    KEEP INDEX;

ALTER TABLE MOVIE_INFO
  DROP
    PRIMARY KEY
    CASCADE
    KEEP INDEX;

ALTER TABLE USER_MILEAGE
  DROP
    PRIMARY KEY
    CASCADE
    KEEP INDEX;

ALTER TABLE BRANCH
  DROP
    PRIMARY KEY
    CASCADE
    KEEP INDEX;

ALTER TABLE JOB
  DROP
    PRIMARY KEY
    CASCADE
    KEEP INDEX;

DROP INDEX PK_USER_INFO;

DROP INDEX PK_EMP_INFO;

DROP INDEX PK_TICKET_PAY;

DROP INDEX PK_CAR_MANAGE;

DROP INDEX PK_MOVIE_INFO;

DROP INDEX PK_USER_MILEAGE;

DROP INDEX PK_BRANCH;

DROP INDEX PK_JOB;

/* 사용자회원정보 */
DROP TABLE USER_INFO 
  CASCADE CONSTRAINTS;

/* 직원정보 */
DROP TABLE EMP_INFO 
  CASCADE CONSTRAINTS;

/* 영화결제 */
DROP TABLE TICKET_PAY 
  CASCADE CONSTRAINTS;

/* 회원등급관리 */
DROP TABLE GRADE_MANAGE 
  CASCADE CONSTRAINTS;

/* 차량관리 */
DROP TABLE CAR_MANAGE 
  CASCADE CONSTRAINTS;

/* 영화정보 */
DROP TABLE MOVIE_INFO 
  CASCADE CONSTRAINTS;

/* 직원근태 */
DROP TABLE EMP_TIMEMANAGE 
  CASCADE CONSTRAINTS;

/* 마일리지 */
DROP TABLE USER_MILEAGE 
  CASCADE CONSTRAINTS;

/* 지점별 상영관리 */
DROP TABLE BRANCH_MOVIE 
  CASCADE CONSTRAINTS;

/* 지점 */
DROP TABLE BRANCH 
  CASCADE CONSTRAINTS;

/* 직책 */
DROP TABLE JOB 
  CASCADE CONSTRAINTS;

/* 회원번호_시퀀스 */
DROP SEQUENCE USER_NO_SEQ;

/* 직원번호_시퀀스 */
DROP SEQUENCE EMP_NO_SEQ;

/* 영화번호_시퀀스 */
DROP SEQUENCE MOVIE_NO_SEQ;

/* 영화결제_시퀀스 */
DROP SEQUENCE TICKET_PAYNO_SEQ;

/* 근태관리번호_시퀀스 */
DROP SEQUENCE TIMEMNG_NO_SEQ;

/* 회원번호_시퀀스 */
CREATE SEQUENCE USER_NO_SEQ 
  INCREMENT BY 1
  START WITH 1;

/* 직원번호_시퀀스 */
CREATE SEQUENCE EMP_NO_SEQ 
  INCREMENT BY 1
  START WITH 1;

/* 영화번호_시퀀스 */
CREATE SEQUENCE MOVIE_NO_SEQ 
  INCREMENT BY 1
  START WITH 1;

/* 영화결제_시퀀스 */
CREATE SEQUENCE TICKET_PAYNO_SEQ 
  INCREMENT BY 1
  START WITH 1;

/* 근태관리번호_시퀀스 */
CREATE SEQUENCE TIMEMNG_NO_SEQ 
  INCREMENT BY 1
  START WITH 1;

/* 사용자회원정보 */
CREATE TABLE USER_INFO (
  USER_NO NUMBER(10) NOT NULL, /* 회원번호 */
  USER_ID VARCHAR2(30) NOT NULL, /* 아이디 */
  USER_PWD VARCHAR2(30) NOT NULL, /* 암호 */
  CARTYPE_NAME VARCHAR2(30) NOT NULL, /* 차종명 */
  USER_NAME VARCHAR2(30), /* 이름 */
  USER_EMAIL VARCHAR2(30), /* 이메일 */
  USER_PHONE VARCHAR2(30) /* 핸드폰 */
);

COMMENT ON TABLE USER_INFO IS '사용자회원정보';

COMMENT ON COLUMN USER_INFO.USER_NO IS '회원번호';

COMMENT ON COLUMN USER_INFO.USER_ID IS '아이디';

COMMENT ON COLUMN USER_INFO.USER_PWD IS '암호';

COMMENT ON COLUMN USER_INFO.CARTYPE_NAME IS '차종명';

COMMENT ON COLUMN USER_INFO.USER_NAME IS '이름';

COMMENT ON COLUMN USER_INFO.USER_EMAIL IS '이메일';

COMMENT ON COLUMN USER_INFO.USER_PHONE IS '핸드폰';

CREATE UNIQUE INDEX PK_USER_INFO
  ON USER_INFO (
    USER_NO ASC
  );

ALTER TABLE USER_INFO
  ADD
    CONSTRAINT PK_USER_INFO
    PRIMARY KEY (
      USER_NO
    );

/* 직원정보 */
CREATE TABLE EMP_INFO (
  EMP_NO NUMBER(10) NOT NULL, /* 사원번호 */
  EMP_ID VARCHAR2(30), /* 아이디 */
  EMP_PWD VARCHAR2(30), /* 암호 */
  EMP_NAME VARCHAR2(30), /* 이름 */
  EMP_BIRTH DATE, /* 생일 */
  EMP_EMAIL VARCHAR2(30), /* 이메일 */
  EMP_PHONE VARCHAR2(30), /* 핸드폰 */
  JOB_NO NUMBER(10), /* 직책번호 */
  BRANCH_NO NUMBER(10) /* 지점번호 */
);

COMMENT ON TABLE EMP_INFO IS '직원정보';

COMMENT ON COLUMN EMP_INFO.EMP_NO IS '사원번호';

COMMENT ON COLUMN EMP_INFO.EMP_ID IS '아이디';

COMMENT ON COLUMN EMP_INFO.EMP_PWD IS '암호';

COMMENT ON COLUMN EMP_INFO.EMP_NAME IS '이름';

COMMENT ON COLUMN EMP_INFO.EMP_BIRTH IS '생일';

COMMENT ON COLUMN EMP_INFO.EMP_EMAIL IS '이메일';

COMMENT ON COLUMN EMP_INFO.EMP_PHONE IS '핸드폰';

COMMENT ON COLUMN EMP_INFO.JOB_NO IS '직책번호';

COMMENT ON COLUMN EMP_INFO.BRANCH_NO IS '지점번호';

CREATE UNIQUE INDEX PK_EMP_INFO
  ON EMP_INFO (
    EMP_NO ASC
  );

ALTER TABLE EMP_INFO
  ADD
    CONSTRAINT PK_EMP_INFO
    PRIMARY KEY (
      EMP_NO
    );

/* 영화결제 */
CREATE TABLE TICKET_PAY (
  TICKET_PAYNO NUMBER(10) NOT NULL, /* 결제번호 */
  USER_NO NUMBER(10) NOT NULL, /* 회원번호 */
  BRANCH_NO NUMBER(10), /* 지점번호 */
  MOVIE_NO NUMBER(10), /* 영화번호 */
  TICKET_PAYTOTAL NUMBER(10), /* 총결제금액 */
  TICKET_PAYCASH NUMBER(10), /* 현금결제금액 */
  MOVIE_PALYDATE DATE, /* 상영일 */
  TICKET_PAYMILEAGE NUMBER(10), /* 마일리지결제금액 */
  TICKET_SALCOUNT NUMBER(10), /* 예매수량 */
  TICKET_PAYDATE DATE /* 결제일자 */
);

COMMENT ON TABLE TICKET_PAY IS '영화결제';

COMMENT ON COLUMN TICKET_PAY.TICKET_PAYNO IS '결제번호';

COMMENT ON COLUMN TICKET_PAY.USER_NO IS '회원번호';

COMMENT ON COLUMN TICKET_PAY.BRANCH_NO IS '지점번호';

COMMENT ON COLUMN TICKET_PAY.MOVIE_NO IS '영화번호';

COMMENT ON COLUMN TICKET_PAY.TICKET_PAYTOTAL IS '총결제금액';

COMMENT ON COLUMN TICKET_PAY.TICKET_PAYCASH IS '현금결제금액';

COMMENT ON COLUMN TICKET_PAY.MOVIE_PALYDATE IS '상영일';

COMMENT ON COLUMN TICKET_PAY.TICKET_PAYMILEAGE IS '마일리지결제금액';

COMMENT ON COLUMN TICKET_PAY.TICKET_SALCOUNT IS '예매수량';

COMMENT ON COLUMN TICKET_PAY.TICKET_PAYDATE IS '결제일자';

CREATE UNIQUE INDEX PK_TICKET_PAY
  ON TICKET_PAY (
    TICKET_PAYNO ASC
  );

ALTER TABLE TICKET_PAY
  ADD
    CONSTRAINT PK_TICKET_PAY
    PRIMARY KEY (
      TICKET_PAYNO
    );

/* 회원등급관리 */
CREATE TABLE GRADE_MANAGE (
  GRADE_NAME VARCHAR2(30), /* 등급이름 */
  GRADE_LOCOUNT NUMBER(10), /* 등급별관람최저기준 */
  GRADE_HICOUNT  NUMBER(10), /* 등급별관람최고기준  */
  GRADE_PCT NUMBER(10,2) /* 적립률 */
);

COMMENT ON TABLE GRADE_MANAGE IS '회원등급관리';

COMMENT ON COLUMN GRADE_MANAGE.GRADE_NAME IS '등급이름';

COMMENT ON COLUMN GRADE_MANAGE.GRADE_LOCOUNT IS '등급별관람최저기준';

COMMENT ON COLUMN GRADE_MANAGE.GRADE_HICOUNT  IS '등급별관람최고기준 ';

COMMENT ON COLUMN GRADE_MANAGE.GRADE_PCT IS '적립률';

/* 차량관리 */
CREATE TABLE CAR_MANAGE (
  CARTYPE_NO NUMBER(10) NOT NULL, /* 차종번호 */
  CARTYPE_NAME VARCHAR2(30), /* 차종명 */
  CARTYPE_PRICE NUMBER(10) /* 책정금액 */
);

COMMENT ON TABLE CAR_MANAGE IS '차량관리';

COMMENT ON COLUMN CAR_MANAGE.CARTYPE_NO IS '차종번호';

COMMENT ON COLUMN CAR_MANAGE.CARTYPE_NAME IS '차종명';

COMMENT ON COLUMN CAR_MANAGE.CARTYPE_PRICE IS '책정금액';

CREATE UNIQUE INDEX PK_CAR_MANAGE
  ON CAR_MANAGE (
    CARTYPE_NO ASC
  );

ALTER TABLE CAR_MANAGE
  ADD
    CONSTRAINT PK_CAR_MANAGE
    PRIMARY KEY (
      CARTYPE_NO
    );

/* 영화정보 */
CREATE TABLE MOVIE_INFO (
  MOVIE_NO NUMBER(10) NOT NULL, /* 영화번호 */
  MOVIE_TITLE VARCHAR2(30), /* 영화제목 */
  MOVIE_POSTER VARCHAR2(50), /* 영화포스터 */
  MOVIE_GENRE VARCHAR2(30), /* 장르 */
  MOVIE_STORY VARCHAR2(30), /* 줄거리 */
  MOVIE_ACTOR VARCHAR2(30), /* 출연진 */
  MOVIE_RUNNINGTIME NUMBER(30) /* 런타임 */
);

COMMENT ON TABLE MOVIE_INFO IS '영화정보';

COMMENT ON COLUMN MOVIE_INFO.MOVIE_NO IS '영화번호';

COMMENT ON COLUMN MOVIE_INFO.MOVIE_TITLE IS '영화제목';

COMMENT ON COLUMN MOVIE_INFO.MOVIE_POSTER IS '영화포스터';

COMMENT ON COLUMN MOVIE_INFO.MOVIE_GENRE IS '장르';

COMMENT ON COLUMN MOVIE_INFO.MOVIE_STORY IS '줄거리';

COMMENT ON COLUMN MOVIE_INFO.MOVIE_ACTOR IS '출연진';

COMMENT ON COLUMN MOVIE_INFO.MOVIE_RUNNINGTIME IS '런타임';

CREATE UNIQUE INDEX PK_MOVIE_INFO
  ON MOVIE_INFO (
    MOVIE_NO ASC
  );

ALTER TABLE MOVIE_INFO
  ADD
    CONSTRAINT PK_MOVIE_INFO
    PRIMARY KEY (
      MOVIE_NO
    );

/* 직원근태 */
CREATE TABLE EMP_TIMEMANAGE (
  EMP_NO NUMBER(10) NOT NULL, /* 사원번호 */
  TIMEMNG_NO NUMBER(10), /* 근태관리번호 */
  EMP_INTIME DATE, /* 출근시간 */
  EMP_OUTTIME DATE /* 퇴근시간 */
);

COMMENT ON TABLE EMP_TIMEMANAGE IS '직원근태';

COMMENT ON COLUMN EMP_TIMEMANAGE.EMP_NO IS '사원번호';

COMMENT ON COLUMN EMP_TIMEMANAGE.TIMEMNG_NO IS '근태관리번호';

COMMENT ON COLUMN EMP_TIMEMANAGE.EMP_INTIME IS '출근시간';

COMMENT ON COLUMN EMP_TIMEMANAGE.EMP_OUTTIME IS '퇴근시간';

/* 마일리지 */
CREATE TABLE USER_MILEAGE (
  USER_NO NUMBER(10) NOT NULL, /* 회원번호 */
  USER_MILEAGE NUMBER(10), /* 마일리지 */
  USER_RSVCOUNT NUMBER(10) /* 예매횟수 */
);

COMMENT ON TABLE USER_MILEAGE IS '마일리지';

COMMENT ON COLUMN USER_MILEAGE.USER_NO IS '회원번호';

COMMENT ON COLUMN USER_MILEAGE.USER_MILEAGE IS '마일리지';

COMMENT ON COLUMN USER_MILEAGE.USER_RSVCOUNT IS '예매횟수';

CREATE UNIQUE INDEX PK_USER_MILEAGE
  ON USER_MILEAGE (
    USER_NO ASC
  );

ALTER TABLE USER_MILEAGE
  ADD
    CONSTRAINT PK_USER_MILEAGE
    PRIMARY KEY (
      USER_NO
    );

/* 지점별 상영관리 */
CREATE TABLE BRANCH_MOVIE (
  MOVIE_NO NUMBER(10) NOT NULL, /* 영화번호 */
  BRANCH_NO NUMBER(10), /* 지점번호 */
  MOVIE_STARTDATE DATE, /* 상영시작일 */
  MOVIE_ENDDATE DATE, /* 상영종료일 */
  MOVIE_START1 VARCHAR2(30), /* 시작시간1 */
  MOVIE_START2 VARCHAR2(30), /* 시작시간2 */
  MOVIE_START3 VARCHAR2(30) /* 시작시간3 */
);

COMMENT ON TABLE BRANCH_MOVIE IS '지점별 상영관리';

COMMENT ON COLUMN BRANCH_MOVIE.MOVIE_NO IS '영화번호';

COMMENT ON COLUMN BRANCH_MOVIE.BRANCH_NO IS '지점번호';

COMMENT ON COLUMN BRANCH_MOVIE.MOVIE_STARTDATE IS '상영시작일';

COMMENT ON COLUMN BRANCH_MOVIE.MOVIE_ENDDATE IS '상영종료일';

COMMENT ON COLUMN BRANCH_MOVIE.MOVIE_START1 IS '시작시간1';

COMMENT ON COLUMN BRANCH_MOVIE.MOVIE_START2 IS '시작시간2';

COMMENT ON COLUMN BRANCH_MOVIE.MOVIE_START3 IS '시작시간3';

/* 지점 */
CREATE TABLE BRANCH (
  BRANCH_NO NUMBER(10) NOT NULL, /* 지점번호 */
  BRANCH_NAME VARCHAR2(30), /* 지점명 */
  BRANCH_CAPACITY NUMBER(10) /* 정원 */
);

COMMENT ON TABLE BRANCH IS '지점';

COMMENT ON COLUMN BRANCH.BRANCH_NO IS '지점번호';

COMMENT ON COLUMN BRANCH.BRANCH_NAME IS '지점명';

COMMENT ON COLUMN BRANCH.BRANCH_CAPACITY IS '정원';

CREATE UNIQUE INDEX PK_BRANCH
  ON BRANCH (
    BRANCH_NO ASC
  );

ALTER TABLE BRANCH
  ADD
    CONSTRAINT PK_BRANCH
    PRIMARY KEY (
      BRANCH_NO
    );

/* 직책 */
CREATE TABLE JOB (
  JOB_NO NUMBER(10) NOT NULL, /* 직책번호 */
  JOB_NAME VARCHAR2(20) /* 직책명 */
);

COMMENT ON TABLE JOB IS '직책';

COMMENT ON COLUMN JOB.JOB_NO IS '직책번호';

COMMENT ON COLUMN JOB.JOB_NAME IS '직책명';

CREATE UNIQUE INDEX PK_JOB
  ON JOB (
    JOB_NO ASC
  );

ALTER TABLE JOB
  ADD
    CONSTRAINT PK_JOB
    PRIMARY KEY (
      JOB_NO
    );

ALTER TABLE EMP_INFO
  ADD
    CONSTRAINT FK_BRANCH_TO_EMP_INFO
    FOREIGN KEY (
      BRANCH_NO
    )
    REFERENCES BRANCH (
      BRANCH_NO
    );

ALTER TABLE TICKET_PAY
  ADD
    CONSTRAINT FK_USER_INFO_TO_TICKET_PAY
    FOREIGN KEY (
      USER_NO
    )
    REFERENCES USER_INFO (
      USER_NO
    );

ALTER TABLE TICKET_PAY
  ADD
    CONSTRAINT FK_MOVIE_INFO_TO_TICKET_PAY
    FOREIGN KEY (
      MOVIE_NO
    )
    REFERENCES MOVIE_INFO (
      MOVIE_NO
    );

ALTER TABLE TICKET_PAY
  ADD
    CONSTRAINT FK_BRANCH_TO_TICKET_PAY
    FOREIGN KEY (
      BRANCH_NO
    )
    REFERENCES BRANCH (
      BRANCH_NO
    );

ALTER TABLE EMP_TIMEMANAGE
  ADD
    CONSTRAINT FK_EMP_INFO_TO_EMP_TIMEMANAGE
    FOREIGN KEY (
      EMP_NO
    )
    REFERENCES EMP_INFO (
      EMP_NO
    );

ALTER TABLE USER_MILEAGE
  ADD
    CONSTRAINT FK_USER_INFO_TO_USER_MILEAGE
    FOREIGN KEY (
      USER_NO
    )
    REFERENCES USER_INFO (
      USER_NO
    );

ALTER TABLE BRANCH_MOVIE
  ADD
    CONSTRAINT FK_MOVIE_INFO_TO_BRANCH_MOVIE
    FOREIGN KEY (
      MOVIE_NO
    )
    REFERENCES MOVIE_INFO (
      MOVIE_NO
    );